---

# - name: Install nginx yum
#   yum:
#     name:
#     - firewalld
#     - nginx
#   state: present
- name: Install nginx
  yum:
    name:
      - firewalld
      - nginx
    state: present

- name: Start and enable nginx systemd service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Start and enable firewalld 
  service:
    name: firewalld
    state: started
    enabled: yes 

- name: Enable firewalld https 
  ansible.posix.firewalld:
    zone: public
    service: https
    permanent: yes
    state: enabled

- name: Enable firewalld http
  ansible.posix.firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled

- name: Enable firewalld 80/tcp
  ansible.posix.firewalld:
    zone: public
    permanent: yes
    state: enabled
    port: 80/tcp

- name: Enable firewalld 443/tcp
  ansible.posix.firewalld:
    zone: public
    permanent: yes
    state: enabled
    port: 443/tcp
  notify: reload firewalld

- name: Create default nginx www directory
  file:
    path: /data/www
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes # Like mkdir -p
    setype: httpd_sys_content_t

- name: Move over nginx config file to remote
  template:
    src: nginx.conf.tmpl
    dest: /etc/nginx/nginx.conf
    setype: httpd_config_t

- name: Move index html to remote
  template:
    src: index.html
    dest: /data/www/index.html
    mode: preserve
    setype: httpd_sys_content_t
  notify: restart nginx

- name: Move over background image
  copy:
    src: BG.jpg
    dest: /data/www/BG.jpg
    mode: preserve
    setype: httpd_sys_content_t
  notify: restart nginx
